url: http://limydesign.ru/
baseurl: 

# Site settings
title: LimyDesign Studio
email: me@arsen.pw
description: "Мы делаем качественные сайты. Ознакомьтесь с нашими работами и нашими ценами. Мы предлагаем отличное сочетание цена-качество."

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: Telegram
    icon: paper-plane
    url: https://telegram.me/limydesign_bot
  - title: Вконтакте
    icon: vk
    url: http://vk.com/limydesign
  - title: Facebook
    icon: facebook
    url: http://fb.me/limydesign
  - title: Github
    icon: github
    url: https://github.com/LimyDesign

# Build settings
markdown: kramdown
permalink: pretty
sass:
  sass_dir: _sass